### ISSUE TITLE
Feature Request - New animations

### ISSUE THREAD

**Issue by ghost** [NNTin/discord-logo#1]
Actually, it's not really new animations; but rather enhancements/settings for one of the current animations. [Specifically, this one.](https://totally-not.a-sketchy.site/d2e8de.png) At the end of the animation, the result is [quite terrible](https://get.banned.today/473f31.png), therefore it would be great to get a version similar to discord's loading screen when it spins infinitely while being hovered, and an other one where it does a complete spin while being hovered and then stops. Just a few thoughts. Actually, that might be a thing already and I'm just a numbnut; who knows.

**Comment by NNTin** [comment]
Closing in favor of https://github.com/NNTin/discord-logo/issues/6.
If this idea gets implemented, add it as an additional separate animation.
