### ISSUE TITLE
Undo commits for background animation (browser no longer supports them)

### ISSUE THREAD

**Issue by NNTin** [NNTin/discord-logo#4]
Undo https://github.com/NNTin/discord-logo/pull/2 and https://github.com/NNTin/discord-logo/pull/3  
Browser support for the background animation was stopped. Those background effects are no longer working.

Short summary of the steps:  
Clone the repo, install the dependencies, run the project locally, create a new commit undoing the changes provided in those two pull request, test locally, generate the new static files in the docs folder and create the pull/merge request.

**Comment by eruhaji** [comment]
I'd like to work on this issue, can you please assign it to me?

**Comment by NNTin** [comment]
solved with https://github.com/NNTin/discord-logo/pull/8
