### ISSUE TITLE
Add general linting rule, CI check for linting and run code through a linter

### ISSUE THREAD

**Issue by NNTin** [NNTin/discord-logo#7]
Something similar to https://github.com/Fubinator/planning-poker-discord-bot/pull/17

**Comment by zurda** [comment]
Hi there, awesome project. Is it OK for me to pick this issue up? 
Thanks

**Comment by NNTin** [comment]
Sure go ahead 👍

**Comment by zurda** [comment]
I created a PR for this, if you get a chance to review: https://github.com/NNTin/discord-logo/pull/13

**Comment by NNTin** [comment]
Thank you for your contribution. Issue fulfilled, closing
